### ISSUE TITLE
Auto-shrink should be disabled from semi-finals to finals

### ISSUE THREAD

**Issue by nathandud** [romrell4/bracket-challenge-ios#13]
The shrink animation from the semi-finals page to the finals page is unnecessary and should be removed.

**Comment by romrell4** [comment]
I have been investigating... On the current device sizes that we use, this may be the case. But in situations such as landscape orientation on small devices, multi-tasking (side-by-side windows), etc, the screen size might be such that the shrink may be helpful. Also, for consistency, I have decided to leave it in.
